### ISSUE TITLE
potential issue with IW.

### ISSUE THREAD

**Issue by MFaisalZaki** [jendrikseipp/scorpion#15]
I tried to solve the [rovers domain instance three](https://github.com/user-attachments/files/16373859/rovers.zip), but IW failed to solve the planning problem. I think there is a potential bug in the implementation since this problem is simple and was solvable using "brfs."

**Comment by jendrikseipp** [comment]
IW is an incomplete algorithm (so it's not guaranteed to find a solution even with unlimited resources), while BrFS is complete.
